name: Deploy Flask app

on:
    workflow_dispatch:

jobs:

    

    deploy-app:

        runs-on: self-hosted

        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER}}


        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Compose
              uses: docker/setup-compose-action@v2

            - name: Deploy the flask app using Docker Compose
              run: docker compose down && docker compose up -d --build --force-recreate


              