#This is the workflow name
name: Hello workflow

# workflow runs on an automatic trigger, which will initiate the workflow whenever a change is pushed to the branch (deployment0
on:
  push:
    branches: [main]
    paths:
      - '*.html'


#These are jobs inside the workflow
jobs:

#greet is the name of the job
  greet:
  # this is GitHub runners, each job runs on a runner
    runs-on: ubuntu-latest
    #jobs are basically steps
    steps:
    #step 1
      - name: say hello to users
        run: echo "Hello, everyone"
    #step 2
      - name: say hello to username
        run: echo "Welcome $USER"

  # this is a new job whose name is details
  details:
  #this is GitHub runners, because each job requires a runner
    runs-on: ubuntu-latest

    steps:
      - name: version of Python and Docker
        run: docker --version && python --version
