# This workflow name is "Portfolio". It is a descriptive name that indicates the purpose of the workflow, which is to deploy a portfolio website.
name: Portfolio

# This workflow trigger is set to activate on two events:
# 1. A push to the main branch: Whenever there is a push to the main branch of the repository, this workflow will be triggered. 
# 2. Manual trigger: The workflow can also be triggered manually using the "workflow_dispatch" event, allowing users to run the workflow on demand from the GitHub Actions interface.
on:
    # push:
    #     branches:
    #         - main
    workflow_dispatch:

# This section defines the permissions required for the workflow to execute. 
# It specifies that the workflow needs read permissions for contents and write permissions for GitHub Pages and ID tokens.
# This is necessary for deploying the portfolio to GitHub Pages and for authentication purposes.            
permissions:
    pages: write
    id-token: write
    contents: read

#This section defines the jobs that will be executed when the workflow is triggered. 
jobs:

    # The "deploy" job is defined here. It will run on the latest version of Ubuntu.
    deploy:
        runs-on: ubuntu-latest

        # The environment section specifies the environment name and URL for the deployment.
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url}}
            

        steps:
            # Step 1 : Get access to your Portfolio code via pre-built actions
            # clones or checks out the code from the repository where this workflow is defined.
            - name: Checkout Code
              uses: actions/checkout@v4

            # Step 2: Setup GitHub pages via pre-built actions
            - name: Setup GitHub Pages
              uses: actions/configure-pages@v4

            # Step 3: Static code artifacts for static website hosting via pre-built actions
            - name: Upload Static Files
              uses: actions/upload-pages-artifact@v4
              with:
                path: '.' 
                # This is the path to the static files. In this case, it is set to the current directory ('.') that need to be uploaded for deployment. 
                
            # Step 4: Deploy to GitHub Pages to make the Page Live via pre-built actions
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
              id: deployment
