# API keys, Sensitive data, credentials, etc. should not be committed to the repository. 
#This workflow scans for secrets in the codebase and alerts if any are found using GitLeaks.

name: Secrets Scan

on:
    workflow_call:

jobs:

    secrets-scan:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0 # Fetch the entire commit history for accurate scanning.
              
            - name: Run GitLeaks Scanner
              uses: gitleaks/gitleaks-action@v2
              env: 
                #This token is automatically provided by GitHub Actions which manages the repository and has permissions to create issues in the repository.
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
